#include "../include/blackwall/blackwall.hpp"
#include "./tenser.cpp"
#include "./neuron.cpp"
#include "./neuralnetwork.cpp"
#include "./activation_function.cpp"
#include "./loss_function.cpp"
#include "./k-nearestneighbours.cpp"
